export class Adquisicion{
    adqid?: number;
    adq_cod_control: string;
    adq_fec_fac_dui: Date;
    adq_nit_ci_prov: string;
    adq_nro_auto: number;
    adq_nro_dui: number;
    adq_nro_fact: number;
    adq_razon_social: string;
    adq_subtotal: number;
    adq_tipo_compra: number;
    adq_total_cred_fiscal: number;
    adq_total_desc_bonif_rebaja_al_iva: number;
    adq_total_importe_base_cred_fiscal: number;
    adq_total_importe_compra: number;
    adq_total_no_sujeto_cred_fiscal: number;
    adqcondicpago: string;
    adqdescrip: string;
    adqdistribuidor: string;
    adqformapago: string;
    adqnotasalida: string;
    adqnro_pedido: string;
    adqobservaciones: string;
    adqreceptor: string;
    adqruta: string;
    adqtrasnporte: string;
    proveedor_id: number;
    usuario_id:number;
    adqfecha:Date;
    estado:string;
}
